package com.spring.demo.dao.user;

import com.spring.demo.model.user.User;

public interface IUserDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * 插入用户信息
     * @param user 用户
     * @return
     */
    int insert(User user);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated
     */
    int insertSelective(User record);

    /**
     * 根据ID查询用户信息
     * @param id 用户ID
     * @return
     */
    public User getUserById(String id);

    /**
     * 根据userNo查询用户信息
     * @param userNo 用户编码
     * @return
     */
    public User getUserByUserNo(String userNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User record);
}