package com.spring.demo.dao.authority;

import com.spring.demo.model.authority.Menu;
import com.spring.demo.model.user.User;

import java.util.List;

public interface IMenuDao {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_menu
     *
     * @mbg.generated
     */
    int insert(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_menu
     *
     * @mbg.generated
     */
    int insertSelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_menu
     *
     * @mbg.generated
     */
    Menu selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Menu record);

    /**
     * 根据当前用户查询菜单
     * @param user
     * @return
     */
    List<Menu> getAllByUser(User user);

    /**
     * 查询所有菜单
     * @return
     */
    List<Menu> getAll();
}